[package]
name = "LuckySurvivor"
version = "1.0.0"
authors = []
edition = "2024.alpha"

[addresses]
lucky_survivor = "_"
deployer = "_"

[dev-addresses]
lucky_survivor = "0xCAFE"
deployer = "0xDE1112"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-framework.git"
rev = "testnet"
subdir = "aptos-framework"

[dev-dependencies]
